---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: databases-stack
  labels: {app.kubernetes.io/name: postgresql, app.kubernetes.io/part-of: databases-stack}
spec:
  # replicas: 0 → motor KAPALI. Dashboard'daki "Aktif Et" bunu 1 yapar.
  replicas: 0
  serviceName: postgresql
  selector:
    matchLabels: {app.kubernetes.io/name: postgresql}
  template:
    metadata:
      labels: {app.kubernetes.io/name: postgresql}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: postgresql
        image: postgres:16
        imagePullPolicy: IfNotPresent
        ports:
        - name: client
          containerPort: 5432
        args:
        - "postgres"
        - "-c"
        - "shared_buffers=$(POSTGRES_SHARED_BUFFERS)"
        - "-c"
        - "effective_cache_size=$(POSTGRES_EFFECTIVE_CACHE)"
        - "-c"
        - "max_connections=$(POSTGRES_MAX_CONNECTIONS)"
        - "-c"
        - "max_worker_processes=$(POSTGRES_MAX_WORKERS)"
        - "-c"
        - "max_locks_per_transaction=$(POSTGRES_MAX_LOCKS)"
        - "-c"
        - "work_mem=$(POSTGRES_WORK_MEM)"
        - "-c"
        - "log_min_duration_statement=2000"
        - "-c"
        - "wal_level=replica"
        - "-c"
        - "hot_standby=on"
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_DB
          value: "defaultdb"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_SHARED_BUFFERS
          value: "512MB"
        - name: POSTGRES_EFFECTIVE_CACHE
          value: "1536MB"
        - name: POSTGRES_MAX_CONNECTIONS
          value: "200"
        - name: POSTGRES_MAX_WORKERS
          value: "8"
        - name: POSTGRES_MAX_LOCKS
          value: "64"
        - name: POSTGRES_WORK_MEM
          value: "4MB"
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: databases-stack
  labels: {app.kubernetes.io/name: postgresql}
spec:
  selector: {app.kubernetes.io/name: postgresql}
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  - name: pgbouncer
    port: 6432
    targetPort: 6432
