---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases-stack
resources:
- namespace.yaml
- engine-mariadb.yaml
- engine-postgresql.yaml
- engine-mongodb.yaml
- engine-redis.yaml
- engine-mssql.yaml
- engine-cassandra.yaml
- engine-elasticsearch.yaml
- engine-kafka.yaml
- engine-rabbitmq.yaml
- engine-clickhouse.yaml
- engine-neo4j.yaml
- engine-minio.yaml
- controller.yaml
- catalog-configmap.yaml
